/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedCarriersRouteImport } from './routes/_authenticated/carriers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDriversRouteImport } from './routes/_authenticated/drivers'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedShippersRouteImport } from './routes/_authenticated/shippers'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedLoadsIndexRouteImport } from './routes/_authenticated/loads/index'
import { Route as AuthenticatedLoadsLoadIdRouteImport } from './routes/_authenticated/loads/$loadId'
import { Route as AuthenticatedLoadsNewRouteImport } from './routes/_authenticated/loads/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarriersRoute = AuthenticatedCarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriversRoute = AuthenticatedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShippersRoute = AuthenticatedShippersRouteImport.update({
  id: '/shippers',
  path: '/shippers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLoadsIndexRoute = AuthenticatedLoadsIndexRouteImport.update({
  id: '/loads/',
  path: '/loads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoadsLoadIdRoute =
  AuthenticatedLoadsLoadIdRouteImport.update({
    id: '/loads/$loadId',
    path: '/loads/$loadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoadsNewRoute = AuthenticatedLoadsNewRouteImport.update({
  id: '/loads/new',
  path: '/loads/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/carriers': typeof AuthenticatedCarriersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/map': typeof AuthenticatedMapRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shippers': typeof AuthenticatedShippersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/loads/$loadId': typeof AuthenticatedLoadsLoadIdRoute
  '/loads/new': typeof AuthenticatedLoadsNewRoute
  '/loads/': typeof AuthenticatedLoadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/carriers': typeof AuthenticatedCarriersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/map': typeof AuthenticatedMapRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shippers': typeof AuthenticatedShippersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/loads/$loadId': typeof AuthenticatedLoadsLoadIdRoute
  '/loads/new': typeof AuthenticatedLoadsNewRoute
  '/loads': typeof AuthenticatedLoadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/carriers': typeof AuthenticatedCarriersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/drivers': typeof AuthenticatedDriversRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shippers': typeof AuthenticatedShippersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/loads/$loadId': typeof AuthenticatedLoadsLoadIdRoute
  '/_authenticated/loads/new': typeof AuthenticatedLoadsNewRoute
  '/_authenticated/loads/': typeof AuthenticatedLoadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/carriers'
    | '/dashboard'
    | '/documents'
    | '/drivers'
    | '/fleet'
    | '/map'
    | '/notifications'
    | '/settings'
    | '/shippers'
    | '/auth/callback'
    | '/loads/$loadId'
    | '/loads/new'
    | '/loads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/carriers'
    | '/dashboard'
    | '/documents'
    | '/drivers'
    | '/fleet'
    | '/map'
    | '/notifications'
    | '/settings'
    | '/shippers'
    | '/auth/callback'
    | '/loads/$loadId'
    | '/loads/new'
    | '/loads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/audit-logs'
    | '/_authenticated/carriers'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/drivers'
    | '/_authenticated/fleet'
    | '/_authenticated/map'
    | '/_authenticated/notifications'
    | '/_authenticated/settings'
    | '/_authenticated/shippers'
    | '/auth/callback'
    | '/_authenticated/loads/$loadId'
    | '/_authenticated/loads/new'
    | '/_authenticated/loads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carriers': {
      id: '/_authenticated/carriers'
      path: '/carriers'
      fullPath: '/carriers'
      preLoaderRoute: typeof AuthenticatedCarriersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers': {
      id: '/_authenticated/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shippers': {
      id: '/_authenticated/shippers'
      path: '/shippers'
      fullPath: '/shippers'
      preLoaderRoute: typeof AuthenticatedShippersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/loads/': {
      id: '/_authenticated/loads/'
      path: '/loads'
      fullPath: '/loads/'
      preLoaderRoute: typeof AuthenticatedLoadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loads/$loadId': {
      id: '/_authenticated/loads/$loadId'
      path: '/loads/$loadId'
      fullPath: '/loads/$loadId'
      preLoaderRoute: typeof AuthenticatedLoadsLoadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loads/new': {
      id: '/_authenticated/loads/new'
      path: '/loads/new'
      fullPath: '/loads/new'
      preLoaderRoute: typeof AuthenticatedLoadsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedCarriersRoute: typeof AuthenticatedCarriersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedDriversRoute: typeof AuthenticatedDriversRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShippersRoute: typeof AuthenticatedShippersRoute
  AuthenticatedLoadsLoadIdRoute: typeof AuthenticatedLoadsLoadIdRoute
  AuthenticatedLoadsNewRoute: typeof AuthenticatedLoadsNewRoute
  AuthenticatedLoadsIndexRoute: typeof AuthenticatedLoadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedCarriersRoute: AuthenticatedCarriersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedDriversRoute: AuthenticatedDriversRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShippersRoute: AuthenticatedShippersRoute,
  AuthenticatedLoadsLoadIdRoute: AuthenticatedLoadsLoadIdRoute,
  AuthenticatedLoadsNewRoute: AuthenticatedLoadsNewRoute,
  AuthenticatedLoadsIndexRoute: AuthenticatedLoadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
